name: harry_potter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  freezed: ^2.4.4
  freezed_annotation: ^2.4.4
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  auto_route: ^9.0.0
  darq: ^2.0.0
  collection: ^1.19.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  intl: ^0.20.2
  cached_network_image: ^3.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/



flutter_gen:
  output: lib/styles/
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false


import_sorter:
    comments: false # Optional, defaults to true